### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by tollmanz** [cedaro/grunt-wp-i18n#4]
@bradyvercher What are your thoughts on adding an option to exclude directories from being processed through the i18n tools? A use case is including a library via a submodule and not including those internationalized strings in the main .pot file. I imagine that this _could_ require modifying the PHP tools. Any thoughts?

**Comment by philiparthurmoore** [comment]
Hey gang. I've been running `grunt makepot` with the following config:

```
		/**
		 * Theme and Plugin internationalization
		 * @see https://github.com/blazersix/grunt-wp-i18n/
		 */
		makepot: {
			target: {
				options: {
					domainPath: '/languages',
					exclude: [
						'node_modules/.*'
					],
					i18nToolsPath: 'languages/tools/i18n',
					potFilename: '<%= pkg.name %>-en_US.pot',
					type: 'wp-theme'
				}
			}
		},

```

There are a few issues here:

1. `node_modules` exclusion isn't working. I know that this was added automatically so it's not needed, but even then `node_modules` stuff shows up:

```
#: node_modules/grunt-wp-i18n/test/fixtures/text-domains/update-all-domains.php:6
#: node_modules/grunt-wp-i18n/test/fixtures/text-domains/update-all-domains.php:7
#: node_modules/grunt-wp-i18n/test/fixtures/text-domains/update-all-domains.php:8
msgctxt "a string"
msgid "String"
msgstr ""
```

2. I suggest adding information into the documentation about i18nToolsPath so that people know they may need to create symbolic links to get that working. Right now I'm getting this output:

```
PHP Warning:  require_once(/Applications/XAMPP/xamppfiles/htdocs/develop/src/wp-content/themes/theme-slug/languages/src/wp-includes/pomo/po.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/develop/src/wp-content/themes/theme-slug/languages/tools/i18n/not-gettexted.php on line 16
```

I want those tools to be tucked away under /languages/ and not rely on the trunk checkout, and it seems that I'm going to have to use symbolic links to make that work.

**Comment by shivapoudel** [comment]
@bradyvercher I am also uncleared about i18nToolsPath, could you please document for it as suggested by @philiparthurmoore xD

**Comment by bradyvercher** [comment]
Hi @philiparthurmoore! The `i18nToolsPath` should really only be defined if you want to use a different version of the i18n tools. It's mainly there as a relic from the initial version before the tools were bundled and adds a bit of flexibility for projects that need it.

Otherwise, the [bundled tools](https://github.com/blazersix/grunt-wp-i18n/tree/develop/vendor/wp-i18n-tools) are used, which have been customized to support the various options, including `exclude`, which is probably why your local copy isn't ignoring those.

Does everything work if you remove that `i18nToolsPath` option?

**Comment by philiparthurmoore** [comment]
Wow. And magically all of the above issues went away when I removed `i18nToolsPath`. Thanks so much @bradyvercher. I lost half a day before posting here; I should post more often.

**Comment by bradyvercher** [comment]
Ouch! Glad to hear that fixed it. Definitely feel free to suggest any improvements and reach out much sooner next time!

**Comment by GaryJones** [comment]
Maybe add a PR into the README that clarifies this so others don't get tripped up too?
